# Generated by Django 5.1.5 on 2025-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Блог-запись', 'verbose_name_plural': 'Блог-записи'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
